In [1]:
import requests
from datetime import datetime, timedelta
import pandas as pd

In [2]:
week = {0:'ПН', 1:'ВТ', 2:'СР', 3:'ЧТ', 4:'ПТ', 5:'СБ', 6:'ВС'}

Дубровка

In [3]:
headers1 = {
'authorization': 'Bearer yusw3yeu6hrr4r9j3gw6, User ec8ecfaf1072c39041a7cc582a8ac232',
'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 OPR/73.0.3856.344'
}

In [5]:
#ближайшие 2 недели, вечер
df1 = pd.DataFrame(columns=['date','week','17:00','18:00','19:00','20:00','21:00','22:00'])
for i in range(14):
    try:
        answer={}
        date = (datetime.today() + timedelta(i)).strftime('%Y-%m-%d')
        answer['week']=week[(datetime.today() + timedelta(i)).weekday()]
        day_resp = requests.get(f'https://n136076.yclients.com/api/v1/book_times/144563/-1/{date}?service_ids%5B%5D=2177728', headers=headers1).json()
        answer['date'] = datetime.strptime(day_resp[0]['datetime'].replace('+0300', ''), '%Y-%m-%dT%H:%M:%S').strftime('%d.%m')
        for time in day_resp:
            if time['time'] in ['17:00','18:00','19:00','20:00','21:00','22:00']:
                answer[time['time']]='+'
        df1 = df1.append(answer, ignore_index=True)
    except IndexError:
        pass
print('Дубровка')
df1.fillna('')

Дубровка

     date week 17:00 18:00 19:00 20:00 21:00 22:00
0   09.02   ВТ     +                             +
1   10.02   СР     +     +                       +
2   11.02   ЧТ                                   +
3   12.02   ПТ     +                 +     +     +
4   13.02   СБ     +     +     +     +     +     +
5   14.02   ВС           +                 +     +
6   15.02   ПН     +     +     +     +     +     +
7   16.02   ВТ     +     +     +                 +
8   17.02   СР     +     +     +                 +
9   18.02   ЧТ     +     +     +           +     +
10  19.02   ПТ     +     +     +     +     +     +
11  20.02   СБ     +     +     +     +     +     +
12  21.02   ВС     +     +     +     +     +     +

Шаболовка

In [6]:
headers2 = {
'authorization': 'Bearer yusw3yeu6hrr4r9j3gw6',
'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 OPR/73.0.3856.344'
}

In [8]:
#ближайшие 2 недели
df1 = pd.DataFrame(columns=['date','week','17:00','18:00','19:00','20:00','21:00','22:00'])
for i in range(14):
    try:
        answer={}
        date = (datetime.today() + timedelta(i)).strftime('%Y-%m-%d')
        answer['week']=week[(datetime.today() + timedelta(i)).weekday()]
        day_resp = requests.get(f'https://n116979.yclients.com/api/v1/book_times/127578/-1/{date}?service_ids%5B%5D=1705604', headers=headers2).json()
        answer['date'] = datetime.strptime(day_resp[0]['datetime'].replace('+0300', ''), '%Y-%m-%dT%H:%M:%S').strftime('%d.%m')
        for time in day_resp:
            if time['time'] in ['17:00','18:00','19:00','20:00','21:00','22:00']:
                answer[time['time']]='+'
        df1 = df1.append(answer, ignore_index=True)
    except IndexError:
        pass
print('Шаболовка')
df1.fillna('')

Шаболовка

     date week 17:00 18:00 19:00 20:00 21:00 22:00
0   08.02   ПН
1   09.02   ВТ     +
2   10.02   СР
3   11.02   ЧТ
4   12.02   ПТ                                   +
5   13.02   СБ                 +     +     +     +
6   14.02   ВС                             +     +
7   15.02   ПН     +                             +
8   16.02   ВТ     +                             +
9   17.02   СР     +                             +
10  18.02   ЧТ     +                             +
11  19.02   ПТ     +     +                 +     +
12  20.02   СБ     +     +     +     +     +     +
13  21.02   ВС     +     +     +     +     +     +

In [ ]:
month = '02'
day = ['01','02','03','04','05']

In [ ]:
for d in day:
    day_resp = requests.get(f'https://n136076.yclients.com/api/v1/book_times/144563/-1/2021-{month}-{d}?service_ids%5B%5D=2177728', headers=headers).json()
    answer = datetime.strptime(day_resp[0]['datetime'].replace('+0300', ''), '%Y-%m-%dT%H:%M:%S').strftime('%d.%m') + ': '
    for time in day_resp:
        answer = answer + time['time'] + ' '
    print(answer)